name: Alpm

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Install Packages
        run: sudo pacman -Syu rust clang gcc --noconfirm --needed

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cargo test --features generate
        working-directory: alpm

  test-git:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
      - name: Install Packages
        run: sudo pacman -Syu rust clang git --noconfirm --needed

      - name: Install Pacman-git
        run: |
          git clone https://aur.archlinux.org/pacman-git
          cd pacman-git
          yes | makepkg -si --nocheck

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cargo test --features generate,git
        working-directory: alpm
